network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no
      addresses:
        - {{IP_ADDRESS}}
      routes:
        - to: default
          via:  {{GATEWAY}}
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
